### 1. 정수 0으로 구성된 크기의 10의 벡터를 만들어 보세요.

In [7]:
import numpy as np
a = np.zeros(10, dtype = int)
a

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### 2. 1에서 만든 배열의 총 바이트 크기를 구하는 코드를 작성해 보세요

In [8]:
import numpy as np
a = np.zeros(10, dtype = int)
print(a.nbytes)

40


### 3. 1에서 만든 배열에서 5번째 값을 1로 변경 해보세요.

In [9]:
import numpy as np
a = np.zeros(10, dtype = int)
a[4] =1
print(a.nbytes)
print(a)

40
[0 0 0 0 1 0 0 0 0 0]


### 4. 10~49까지의 정수 값을 연속적으로 가지는 벡터를 만들어 보세요

In [10]:
import numpy as np 
a = np.arange(10,50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


### 5. 4번에서 생성한 벡터를 역순으로 출력하는 코드를 작성하세요

In [11]:
import numpy as np 
a = np.arange(10,50)
b = a[::-1]
print(b)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


### 6. 0에서 8까지의 값을 가지는 1차원 배열을 3x3(2차원)배열로 바꿔보세요.

In [12]:
import numpy as np 
a = np.arange(0,9)
print(a)
b = a.reshape(3,3)
print(b)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


### 7. [1,2,0,0,4,0]에서 0이 아닌 원소의 위치를 저장한 배열을 만들어 보세요.(array[0,1,4]가 출력되도록 합니다.)

In [13]:
import numpy as np
a = np.array([1,2,0,0,4,0])
b = np.where(a != 0)
print(b)

(array([0, 1, 4], dtype=int64),)


### 8. 랜덤값을 갖는 3x3x3 배열을 생성 하세요.

In [14]:
import numpy as np
a = np.random.random((3,3,3))
a

array([[[0.41248858, 0.98496911, 0.68058737],
        [0.33306115, 0.10413544, 0.64309868],
        [0.87338727, 0.56943765, 0.91936082]],

       [[0.49148621, 0.06600774, 0.57083713],
        [0.02610798, 0.34402854, 0.18203885],
        [0.49029576, 0.12526708, 0.19800579]],

       [[0.27324063, 0.57097909, 0.48086013],
        [0.9833701 , 0.30017226, 0.55149407],
        [0.48145134, 0.01846643, 0.28086299]]])

### 9. 랜덤하게 생성된 10x10 배열의 최대, 최소 값을 찾아 출력하라.

In [15]:
import numpy as np
a = np.random.random((10,10))
# np.argmax(a), np.argmin(a)
a.max(), a.min()

(0.9980207950360961, 0.0073175993035554665)

### 10. 30개의 랜덤한 정수값을 갖는 배열을 생성하고, 모든 값의 평균을 출력하라.

In [16]:
import numpy as np
a = np.random.randint(100, size=30)
print(a)
a.mean()

[27 29 47 22 98 59 82  7 46  3 54 53 40  5 82 98 73 17 34 64 95  0  6 58
 78 48 77 32 46  4]


46.13333333333333

### 11. 10x10 배열을 가장 외곽은 모두 1, 안쪽은 모두 0으로 채워지도록 생성하라.

In [17]:
import numpy as np
a = np.full((10,10),1)
a[1:-1,1:-1] =0
a

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

### 12. 11과 반대로 외곽은 0, 안쪽을 모두 1이 채워지도록 하라.

In [18]:
import numpy as np
a = np.full((10,10),0)
a[1:-1,1:-1] =1
a

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

### 13. 8x8 배열에서 홀수 열은 0,1 순으로 , 짝수열은 1,0 순으로 반복되도록 채워라.

In [19]:
import numpy as np
a = np.full((8,8),0)
a[1::2,::2] = 1
a[::2,1::2] = 1
a

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

### 14. 정규분포를 따르는 5x5 배열의 랜덤 값을 생성하라.

In [20]:
import numpy as np
a = np.random.normal(0,1,(5,5))
a

array([[ 0.36978153, -0.10287015, -3.24897123, -0.56039048,  2.77080725],
       [-1.94248621,  0.68428745,  1.60787754,  0.0603451 , -0.54450979],
       [-2.3644566 , -0.49445968,  1.39032447, -1.52494135, -0.179498  ],
       [-0.41129189, -1.2587225 ,  0.40265843,  0.36529747, -0.87445397],
       [-1.73188949, -0.24425284,  0.47852078, -1.30424361,  1.21401775]])

### 15. 0에서 10까지의 10개의 데이터를 1차원 배열에 생성하고, 4~7만 음수로 바꾸는 코드를 작성하라.ex)([0,1,2,3,-4,-5,-6,-7,8,9,10])

In [21]:
import numpy as np
a = np.arange(0,11)
a[4:8]*=(-1)
a
# np.where( (a>=4) & (a<=7), a*(-1), a)

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10])

### 16. 랜덤하게 생성된 10개의 값에서 가장 큰 값을 0으로 채워라.

In [22]:
import numpy as np
a = np.random.randint(100, size=10)
a[np.argmax(a)] = 0
a

array([74,  3, 58, 77, 68, 39, 42, 22,  0, 32])

### 17. 다음 2차원 배열을 생성하고, 아래1), 2), 3)과 같이 출력하라
arr_2d = np.arange(10),reshape(2,5)
arr_2d

     1) array([[5,6,7,8,9],
               [0,1,2,3,4]])
     2) array([[4,3,2,1,0],
               [9,8,7,6,5]])
     3) array([[9,8,7,6,5],
              [4,3,2,1,0]])

In [23]:
import numpy as np
arr_2d = np.arange(10).reshape(2,5)
arr_2d

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [24]:
arr_2d[::-1,:]  # (1)

array([[5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4]])

In [25]:
arr_2d[::,::-1]  # (2)

array([[4, 3, 2, 1, 0],
       [9, 8, 7, 6, 5]])

In [26]:
arr_2d[::-1,::-1] # (3)

array([[9, 8, 7, 6, 5],
       [4, 3, 2, 1, 0]])