### 1. 정수 0으로 구성된 크기의 10의 벡터를 만들어 보세요.

In [2]:
import numpy as np
a = np.zeros(10, dtype = int)
a

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### 2. 1에서 만든 배열의 총 바이트 크기를 구하는 코드를 작성해 보세요

In [3]:
import numpy as np
a = np.zeros(10, dtype = int)
print(a.nbytes)

40


### 3. 1에서 만든 배열에서 5번째 값을 1로 변경 해보세요.

In [4]:
import numpy as np
a = np.zeros(10, dtype = int)
a[4] =1
print(a.nbytes)
print(a)

40
[0 0 0 0 1 0 0 0 0 0]


### 4. 10~49까지의 정수 값을 연속적으로 가지는 벡터를 만들어 보세요

In [5]:
import numpy as np 
a = np.arange(10,50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


### 5. 4번에서 생성한 벡터를 역순으로 출력하는 코드를 작성하세요

In [23]:
import numpy as np 
a = np.arange(10,50)
b = a[::-1]
print(b)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


### 6. 0에서 8까지의 값을 가지는 1차원 배열을 3x3(2차원)배열로 바꿔보세요.

In [7]:
import numpy as np 
a = np.arange(0,9)
print(a)
b = a.reshape(3,3)
print(b)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


### 7. [1,2,0,0,4,0]에서 0이 아닌 원소의 위치를 저장한 배열을 만들어 보세요.(array[0,1,4]가 출력되도록 합니다.)

In [8]:
import numpy as np
a = np.array([1,2,0,0,4,0])
b = np.where(a != 0)
print(b)

(array([0, 1, 4], dtype=int64),)


### 8. 랜덤값을 갖는 3x3x3 배열을 생성 하세요.

In [9]:
import numpy as np
a = np.random.random((3,3,3))
a

array([[[0.9478314 , 0.31524969, 0.10036025],
        [0.70713673, 0.36970769, 0.513773  ],
        [0.74410924, 0.53707169, 0.54670591]],

       [[0.90012785, 0.97624531, 0.75771783],
        [0.26150635, 0.96163787, 0.88020164],
        [0.64323805, 0.15166836, 0.24936202]],

       [[0.27159213, 0.32580802, 0.75869111],
        [0.89316297, 0.19977289, 0.82354889],
        [0.28977454, 0.16128079, 0.31492846]]])

### 9. 랜덤하게 생성된 10x10 배열의 최대, 최소 값을 찾아 출력하라.

In [12]:
import numpy as np
a = np.random.random((10,10))
# np.argmax(a), np.argmin(a)
a.max(), a.min()

(0.9986465805272585, 0.00657968220745242)

### 10. 30개의 랜덤한 정수값을 갖는 배열을 생성하고, 모든 값의 평균을 출력하라.

In [27]:
import numpy as np
a = np.random.randint(100, size=30)
print(a)
a.mean()

[84 83  3 70  3 54  4 86 85 76 62 16 37 86 89 22 74 59 63 63 66 63 67  5
 85  1 38 70 75 40]


54.3

### 11. 10x10 배열을 가장 외곽은 모두 1, 안쪽은 모두 0으로 채워지도록 생성하라.

In [58]:
import numpy as np
a = np.full((10,10),1)
a[1:-1,1:-1] =0
a

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

### 12. 11과 반대로 외곽은 0, 안쪽을 모두 1이 채워지도록 하라.

In [59]:
import numpy as np
a = np.full((10,10),0)
a[1:-1,1:-1] =1
a

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

### 13. 8x8 배열에서 홀수 열은 0,1 순으로 , 짝수열은 1,0 순으로 반복되도록 채워라.

In [49]:
import numpy as np
a = np.full((8,8),0)
a[1::2,::2] = 1
a[::2,1::2] = 1
a

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

### 14. 정규분포를 따르는 5x5 배열의 랜덤 값을 생성하라.

In [30]:
import numpy as np
a = np.random.normal(0,1,(5,5))
a

array([[-1.62874127,  0.18952527, -0.4882554 ,  0.38427988, -1.16115318],
       [ 0.6642054 ,  0.33966126, -0.26047603, -0.68798004, -0.05955575],
       [-0.15381463, -0.37217319,  2.36755341,  0.52063423, -0.09591875],
       [-0.15773535, -0.54348478, -0.10552166, -0.18856894, -0.11275656],
       [-1.53627787,  1.61826652, -0.18281276, -0.88689462, -0.86718325]])

### 15. 0에서 10까지의 10개의 데이터를 1차원 배열에 생성하고, 4~7만 음수로 바꾸는 코드를 작성하라.ex)([0,1,2,3,-4,-5,-6,-7,8,9,10])

In [64]:
import numpy as np
a = np.arange(0,11)
a[4:8]*=(-1)
a
# np.where( (a>=4) & (a<=7), a*(-1), a)

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10])

### 16. 랜덤하게 생성된 10개의 값에서 가장 큰 값을 0으로 채워라.

In [33]:
import numpy as np
a = np.random.randint(100, size=10)
a[np.argmax(a)] = 0
a

array([54, 34, 87, 52, 45, 69, 66,  0, 86, 28])

### 17. 다음 2차원 배열을 생성하고, 아래1), 2), 3)과 같이 출력하라
arr_2d = np.arange(10),reshape(2,5)
arr_2d

     1) array([[5,6,7,8,9],
               [0,1,2,3,4]])
     2) array([[4,3,2,1,0],
               [9,8,7,6,5]])
     3) array([[9,8,7,6,5],
              [4,3,2,1,0]])

In [56]:
import numpy as np
arr_2d = np.arange(10).reshape(2,5)
arr_2d

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [5]:
# arr_2d[::-1][::-1,::-1]


In [4]:
arr_2d[::-1,:]

# arr_2d[:,::-1]

array([[5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4]])

In [15]:
arr_2d[::-1,:]

array([[5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4]])

In [7]:
arr_2d[::-1,::-1]

array([[9, 8, 7, 6, 5],
       [4, 3, 2, 1, 0]])

In [11]:
x2 = np.random.randint(10, size=(3,4))
x2

array([[7, 5, 8, 2],
       [3, 9, 2, 8],
       [1, 7, 9, 4]])

In [12]:
x2.strides

(16, 4)

In [16]:
x = [1,2,3,4,5]
x1 = np.array(x)
x1

array([1, 2, 3, 4, 5])

In [23]:
x1[-2], x1[3]

(4, 4)

In [37]:
x2 = np.arange(1,16)
x2 = np.linspace(1,16,16,dtype=int)
x2.reshape(4,4)


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [55]:
x2 = np.arange(1,17).reshape(4,4)
x2[3:0:-1,:]

array([[13, 14, 15, 16],
       [ 9, 10, 11, 12],
       [ 5,  6,  7,  8]])

In [60]:
src = [ [1,2,3,4], [5,6,7,8],[9,10,11,12],[13,14,15,16] ]
arr = np.array(src)

arr[ arr%2==0 ]

array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [74]:
import numpy as np
aaa = np.array([1,2,3])
bbb = aaa.reshape(-1,1)
ccc1 = bbb[:, np.newaxis]
ccc2 = bbb[np.newaxis,:]
aaa, bbb, ccc1, ccc2

(array([1, 2, 3]),
 array([[1],
        [2],
        [3]]),
 array([[[1]],
 
        [[2]],
 
        [[3]]]),
 array([[[1],
         [2],
         [3]]]))

In [76]:
import numpy as np
x = np.arange(1,13).reshape(3,4)
x


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [78]:
x.sum(axis=0)

array([15, 18, 21, 24])

In [81]:
x.sum(axis=1)

array([10, 26, 42])

In [82]:
p = np.array([[1,2],[3,4]])
np.prod(p), np.prod(p, axis=0), np.prod(p, axis=1)

(24, array([3, 8]), array([ 2, 12]))

In [83]:
import numpy as np
x = np.arange(1,13).reshape(2,3,2)
x

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [85]:
x.sum(axis=0), x.sum(axis=1), x.sum(axis=2)

(array([[ 8, 10],
        [12, 14],
        [16, 18]]),
 array([[ 9, 12],
        [27, 30]]),
 array([[ 3,  7, 11],
        [15, 19, 23]]))

In [90]:
import numpy as np
a = np.array([[1,2],[3,4]])
b = np.array([[5,6]])
np.concatenate((a,b.T), axis =1)

array([[1, 2, 5],
       [3, 4, 6]])

In [108]:
x = np.array([1,2,3])
y = np.array([3,2,1])
z = np.array([4,5])
np.hstack((x,y,z))

array([1, 2, 3, 3, 2, 1, 4, 5])

In [110]:
t = [10,20,30,40,50,60,70,80,90,100]
x1,x2,x3,x4,x5 = np.split(t, [1,3,5,7])
x1,x2,x3,x4,x5

(array([10]),
 array([20, 30]),
 array([40, 50]),
 array([60, 70]),
 array([ 80,  90, 100]))

In [116]:
x = np.arange(1,101).reshape(10,10)
print(x)
t1, t2, b1, b2 = np.hsplit(x, [2,4,6])
t1,t2,b1,b2

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


(array([[ 1,  2],
        [11, 12],
        [21, 22],
        [31, 32],
        [41, 42],
        [51, 52],
        [61, 62],
        [71, 72],
        [81, 82],
        [91, 92]]),
 array([[ 3,  4],
        [13, 14],
        [23, 24],
        [33, 34],
        [43, 44],
        [53, 54],
        [63, 64],
        [73, 74],
        [83, 84],
        [93, 94]]),
 array([[ 5,  6],
        [15, 16],
        [25, 26],
        [35, 36],
        [45, 46],
        [55, 56],
        [65, 66],
        [75, 76],
        [85, 86],
        [95, 96]]),
 array([[  7,   8,   9,  10],
        [ 17,  18,  19,  20],
        [ 27,  28,  29,  30],
        [ 37,  38,  39,  40],
        [ 47,  48,  49,  50],
        [ 57,  58,  59,  60],
        [ 67,  68,  69,  70],
        [ 77,  78,  79,  80],
        [ 87,  88,  89,  90],
        [ 97,  98,  99, 100]]))