In [1]:
# ! pip install numpy

In [2]:
import numpy as np

In [3]:
# numpy는 한 종류의 type으로 배열을 만든다.
a = np.array([1, 2, 3, 4.0, 5.0])
a
type(a)

numpy.ndarray

In [4]:
# 명시적으로 타입을 지정하여 numpy 배열을 생성한다.
a = np.array([1,2,3], dtype='float32')
type(a)

numpy.ndarray

In [9]:
np.array([[[1,2],[3,4],[5,6]]]) # 1x3x2

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [8]:
np.zeros((1,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [13]:
a  = np.arange(10)
# type(a)
a.dtype

dtype('int32')

In [14]:
# 10 => 하나의 행, 10개의 열
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [15]:
np.ones((3,5), dtype=float) # 행=3, 열=5

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
np.full((3,5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [17]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [18]:
# 중요 합니다. 0과 1사이를 5개로 균등 분할. => 그래프
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [19]:
np.eye(5) # 5x5 대각행렬

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [20]:
np.random.random((3,3))

array([[0.74194395, 0.18823425, 0.32381466],
       [0.11261742, 0.90570662, 0.54616795],
       [0.61281854, 0.20263418, 0.36911764]])

In [21]:
# 정규분포는 일종의 정규화 된 분포, 자연, 곡선, log...
# 성적을 냈을때 큰 값과 작은값보다 평균적인 값이 많다. 
# 모집단(전체 집단)을 많이 모아 놓으면 정규분포를 따른다.
# mean : 평균, std :편차
np.random.normal(0, 1,(3,3))

array([[ 0.06237144, -0.80249256, -1.04819671],
       [-0.63285519,  0.67002478, -1.27587813],
       [-0.33165981, -0.56408012, -2.16743263]])

In [22]:
np.random.randint(1, 45,(5,6))

array([[26, 24, 26,  9, 11, 26],
       [25, 13, 38,  8, 15,  5],
       [35, 24,  9, 32, 30,  4],
       [20, 40, 18, 43, 22, 15],
       [42,  3, 39, 29,  4,  9]])

In [24]:
np.empty(shape=(10))

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [25]:
np.ones((2,2), dtype=int)

array([[1, 1],
       [1, 1]])

In [27]:
# 배열의 크기는 같고 모든 원소가 1인 배열을 생성환다.
np.ones_like([1,2,3,4,5,6], dtype=int)

array([1, 1, 1, 1, 1, 1])

In [28]:
np.ones_like([[1,2,3],[4,5,6]], dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [33]:
 # 정방단위행렬 종류: 대각, 단위, 삼각행렬 있다.대각행렬 아래 행렬에 1을 채운다.
np.eye(3, k=-1)

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [31]:
# 대각행렬에 1을 채우고, 나머지는 0으로 채움=> 단위행렬
np.identity(n=3) nXn 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
x2 = np.random.randint(10, size=(3,4))

In [37]:
x2

array([[7, 5, 0, 7],
       [5, 1, 9, 0],
       [0, 7, 2, 2]])

In [38]:
x2.strides # dimensions를 건너가는데(행) 몇 byte? 
# [7,5,0,7]의 용량과 같으므로 4byte인 int32형이 4개 = 16byte.
# 그래서(16,4)로 표현

(16, 4)

In [39]:
x2.ndim # 차원의 개수

2

In [40]:
x2.shape  # 차원의 크기 (NxM)

(3, 4)

In [41]:
x2.size #원소의 갯수

12

In [44]:
x2.dtype  # data type

dtype('int32')

In [42]:
x2.itemsize #원소하나의 크기 int32는 4byte

4

In [45]:
x2.nbytes #size (12) * itemsize (4)

48

In [46]:
x = [1,2,3,4,5]
x1 = np.array(x)
x1

array([1, 2, 3, 4, 5])

In [47]:
x1[0] #첫번째 원소

1

In [48]:
x1[0] =123 #첫번째 원소값을 123으로 변경
x1

array([123,   2,   3,   4,   5])

In [49]:
x1[-1]  # 마지막 원소

5

In [51]:
x1[-2] # 뒤에서 2번째 원소

4

In [52]:
x1[-1],x1[-2]

(5, 4)

In [53]:
x1[0:3] # 첫번째 원소부터 3개

array([123,   2,   3])

In [54]:
x1[3:] # 4번째 원소부터 모두

array([4, 5])

In [55]:
x1

array([123,   2,   3,   4,   5])

In [57]:
x1[:-1] # 처음부터 마지막 원소 제외한 원소들

array([123,   2,   3,   4])

In [63]:
x1[0:], x1[:] # 모든 원소 


(array([0, 0, 0, 0, 0]), array([0, 0, 0, 0, 0]))

In [64]:
x1[:]=0 #모든 원소를 0으로 채워라.
x1[0:3]=1 # 첫번째 부터 3번째 까지 1로 채워라.
x1

array([1, 1, 1, 0, 0])

In [94]:
x2 = np.arange(1,17)
a = x2.reshape(4,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [108]:
a[:],a[0:],a[:,:],a[0:,0:], a[::],a[:,::]  #배열 전체

(array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]]),
 array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]]),
 array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]]),
 array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]]),
 array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]]),
 array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]]))

In [100]:
a[0:1, 0:] # 첫행

array([[1, 2, 3, 4]])

In [102]:
a[0:1,0:1] # 첫번째 행, 첫번째 열

array([[1]])

In [103]:
a[0:1, 0:2] # 첫번째 행, 첫번째 열부터 2개

array([[1, 2]])

In [104]:
a[0:1, 0:3] # 첫번째 행, 첫번째 열부터 3개

array([[1, 2, 3]])

In [105]:
a[0:1, 0:1] #행도 하나, 열도 하나

array([[1]])

In [106]:
a[0:2, 0:1] # 행은 2개 , 열은 하나

array([[1],
       [5]])

In [107]:
a[0:3, 0:1] # 행은 3개 , 열은 하나

array([[1],
       [5],
       [9]])

In [110]:
a[:]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [109]:
a[0::2, ::] # 1행부터 2씩증가 , 열은 전체

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [111]:
a[1::2, 0::2] # 두번째 행부터 2씩 증가, 열은 처음부터 2씩증가

array([[ 5,  7],
       [13, 15]])

In [112]:
# masking : 참인것은 담고 거짓인 것은 버린다.
data = np.array([1,2,3,4,5])
mask = np.array([True, False, False, True, True])
data[mask]

array([1, 4, 5])

In [117]:
x2 = np.arange(1,17)
a = x2.reshape(4,4)
type(a)

numpy.ndarray

In [118]:
mask = (a %2 ==0)
mask
a[mask]

array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [121]:
x =np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [123]:
x[:5] # 처음부터 5개(5번째 까지)

array([0, 1, 2, 3, 4])

In [124]:
x[5:]# 6번째 부터 끝까지

array([5, 6, 7, 8, 9])

In [125]:
x[3:6]# 4번째 부터 6번째 까지

array([3, 4, 5])

In [126]:
x[0:9:2]  # 처음부터 9번째 까지 간격은 2

array([0, 2, 4, 6, 8])

In [127]:
x[::2], x[1::2] # 처음부터 끝까지 간격2, 2번째부터 끝까지 간격2

(array([0, 2, 4, 6, 8]), array([1, 3, 5, 7, 9]))

In [128]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [130]:
a[:2,]# 2개의 행, 열은 전부

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [131]:
a[:2,:2] #2개의 행, 2개의 열

array([[1, 2],
       [5, 6]])

In [132]:
a[::2, ::2] # 처음부터 끝까지 step 2인 행, 첫열부터 끝까지 step 2인 열

array([[ 1,  3],
       [ 9, 11]])

In [133]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [134]:
x2 = np.arange(1,21)
a2 = x2.reshape(4,5)
a2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [138]:
# 복제(copy)가 일어나지 않는 상황이 view
a2_view = a2[1::,::2]
a2_view

array([[ 6,  8, 10],
       [11, 13, 15],
       [16, 18, 20]])

In [141]:
# view는 배열 값이 바뀐다.
a2_view[0,0] = 1234;
a2

array([[   1,    2,    3,    4,    5],
       [1234,    7,    8,    9,   10],
       [  11,   12,   13,   14,   15],
       [  16,   17,   18,   19,   20]])

In [140]:
# copy는 새로운 배열이 생성된다.
a2_copy = a2[1::,::2].copy()
a2_copy

array([[ 6,  8, 10],
       [11, 13, 15],
       [16, 18, 20]])

In [143]:
# copy는 배열의 값이 바꿔지지 않는다.
a2_copy[0,0] = 9999
a2

array([[   1,    2,    3,    4,    5],
       [1234,    7,    8,    9,   10],
       [  11,   12,   13,   14,   15],
       [  16,   17,   18,   19,   20]])

In [ ]:
# reshape - 차원을 자유자재로 바꿔준다. 중요합니다.
# 행이 몇개인지 잘모르겠다... 이럴경우
# 열은 하나로 만들어야 겠다. 
# => 관측치를 하나로 만들어야 훈련을 할수 있다.

In [144]:
matrics = np.arange(1,9)
matrics

array([1, 2, 3, 4, 5, 6, 7, 8])

In [145]:
matrics.reshape((2,4)) # 2*4 = 8

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [146]:
matrics.reshape((2,2,2)) # 2*2*2 = 8

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [147]:
#  열은 1로, 모든 엘리먼트는 줄 맞춰진다.
matrics.reshape(-1,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [154]:
v = np.array([1,2,3])
v.reshape((1,3))

array([[1, 2, 3]])

In [182]:
# 같은 결과값. 열은 1개 , 행 맞춤
v.reshape(3,1), v.reshape(-1,1), v[:,np.newaxis]

(array([[1],
        [2],
        [3]]),
 array([[1],
        [2],
        [3]]),
 array([[1],
        [2],
        [3]]))

In [158]:
v.flatten()

array([1, 2, 3])

In [159]:
# 다차원을 1차원으로 강제 변환
a2.flatten()

array([   1,    2,    3,    4,    5, 1234,    7,    8,    9,   10,   11,
         12,   13,   14,   15,   16,   17,   18,   19,   20])

In [ ]:
# 배열 연산
# axis(중심축)
# 연산을 취할때 방향을 결정한다. axis =0이면 행방향, axis=1이면 열방향.

In [160]:
x = np.arange(1,13).reshape(3,4)
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [161]:
x.sum(axis=0)

array([15, 18, 21, 24])

In [162]:
x.sum(axis=1)

array([10, 26, 42])

In [163]:
p = np.array([[1,2],[3,4]])
p

array([[1, 2],
       [3, 4]])

In [164]:
np.prod(p) # 모든 원소의 곱 1*2*3*4

24

In [165]:
np.prod(p, axis=0) # 1*3, 2*4

array([3, 8])

In [166]:
np.prod(p, axis=1) # 1*2, 3*4

array([ 2, 12])

In [167]:
x = np.arange(1,13).reshape(2,3,2) #2*3*2 = 12
x

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [168]:
x = np.array([1,2,3])
y = np.array([3,2,1])
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [169]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6]])
a, b


(array([[1, 2],
        [3, 4]]),
 array([[5, 6]]))

In [171]:
np.concatenate((a,b), axis =0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [174]:
b.T

array([[5],
       [6]])

In [173]:
np.concatenate((a,b.T), axis =1)

array([[1, 2, 5],
       [3, 4, 6]])

In [175]:
x = np.array([1,2,3])
y = np.array([3,2,1])
np.vstack((x,y))  #열우선 stack

array([[1, 2, 3],
       [3, 2, 1]])

In [177]:
x = np.array([1,2,3])
y = np.array([3,2,1])
z = np.array([4,5,6])
np.hstack((x,y,z))  #행우선 stack

array([1, 2, 3, 3, 2, 1, 4, 5, 6])

In [178]:
x = np.array([[1],[2]]) # 2x1
x

array([[1],
       [2]])

In [179]:
y = np.array([[3],[4]]) # 2x1
y

array([[3],
       [4]])

In [180]:
np.vstack((x,y))

array([[1],
       [2],
       [3],
       [4]])

In [187]:
x = [1,2,3,4,5,6,7,8,9]
print(x[3:7]) # [4,5,6,7]
x1, x2, x3 = np.split(x, [3,7])
x1,x2,x3

[4, 5, 6, 7]


(array([1, 2, 3]), array([4, 5, 6, 7]), array([8, 9]))

In [188]:
grid = np.arange(16).reshape(4,4)
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [192]:
top,bottom = np.vsplit(grid,[2])
top,bottom

(array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]))

In [193]:
left,right = np.hsplit(grid,[2])
left,right

(array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]]))

In [194]:
x1 = np.arange(1,10).reshape(3,3)
x2 = np.arange(1,10).reshape(3,3)
x1,x2

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]))

In [195]:
x1 * x2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [201]:
x3 = np.arange(1,4).reshape(3,1)
x3

array([[1],
       [2],
       [3]])

In [203]:
x1.dot(x3), x1

(array([[14],
        [32],
        [50]]),
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]))