In [4]:
import numpy as np

x=np.int32(1234)
print(x.dtype)
arr = np.arange(5,dtype = 'f')
print(arr)
print(np.int8(arr))
a = np.array([1,2,3,4.0,'aaa'])
print(a)
type(a[0])

np.array([1,2,3,4.5,5.5],dtype='float32')
np.array([[1,2,3],[4,5,6],[7,8,9]])


int32
[0. 1. 2. 3. 4.]
[0 1 2 3 4]
['1' '2' '3' '4.0' 'aaa']


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## 동적인 타입 변환

In [6]:
L1 = list(range(10))
L2 = [str(c) for c in L1]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

# - 서로 다른 타입을 하나의 리스트

In [7]:
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
np.ones((3,5), dtype = float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [11]:
np.full((3,5), 1.0)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [18]:
np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [22]:
x = np.random.random((3,3))
x

array([[0.81530847, 0.06057343, 0.98898079],
       [0.05571776, 0.41618519, 0.31380596],
       [0.29757251, 0.77747476, 0.76612252]])

In [24]:
np.random.normal(0,1,(3,3))

array([[ 1.3599375 ,  0.14662289, -0.51812937],
       [ 1.59114473, -1.74107428, -0.30163191],
       [-2.4823803 , -0.41010688, -0.02662108]])

In [28]:
np.empty( shape=(10))

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [31]:
m = np.arange(30).reshape(5,6)
m
np.ones_like(m)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [33]:
import numpy as np # 모듈 생성
x1 = np.random.randint(10, size =3)
x2 = np.random.randint(10, size =(3,4))
x3 = np.random.randint(10, size =(3,4,5))
print( x3.ndim ) # 차원의 개수
print( x3.shape ) # 각 차원의 크기
print( x3.size )
print( x3.dtype) 
print(x3.itemsize)
print(x3.nbytes) 

3
(3, 4, 5)
60
int32
4
240


In [44]:
x2 = [[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]
a = np.array(x2)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [45]:
a[:]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [40]:
a[ 0:1 , 0:1 ], a[0:1, 0:2], a[0:1, 0:3]

(array([[1]]), array([[1, 2]]), array([[1, 2, 3]]))

In [41]:
a[ 0:1 , 0:1 ], a[0:2, 0:1], a[0:3, 0:1]

(array([[1]]),
 array([[1],
        [5]]),
 array([[1],
        [5],
        [9]]))

In [42]:
a[0::2, ::]

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [46]:
a[1::2, 0::2] = 0
a[:]

array([[ 1,  2,  3,  4],
       [ 0,  6,  0,  8],
       [ 9, 10, 11, 12],
       [ 0, 14,  0, 16]])

In [47]:
import numpy as np
data = np.array([1,2,3,4,5])
mask = np.array([True, False, False, True, True])

result = data[mask]
result

array([1, 4, 5])

In [54]:
src = [ [1,2,3,4], [5,6,7,8], [9,10,11,12], [13,14,15,16] ]
arr = np.array(src)

mask = (arr %2 ==1)
result = arr[ arr%2 == 1]
result



array([ 1,  3,  5,  7,  9, 11, 13, 15])

In [57]:
p = np.array([ [1,2],[3,4] ])
np.prod(p), np.prod(p, axis=0), np.prod(p, axis=1)

(24, array([3, 8]), array([ 2, 12]))

### 1.정수 0으로 구성된 크기의 10의 벡터를 만들어 보세요

In [2]:
import numpy as np
a = np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### 2. 1에서 만든 배열의 총 바이트 크기를 구하는 코드를 작성해 보세요.

In [6]:
import numpy as np
a = np.zeros(10, dtype = int)
print(a.nbytes)

40


### 3. 1에서 만든 배열에서 5번째 값을 1로 변경 해 보세요.

In [7]:
import numpy as np
a = np.zeros(10, dtype = int)
a[4] =1
print(a.nbytes)
print(a)

40
[0 0 0 0 1 0 0 0 0 0]


### 4. 10~49까지의 정수 값을 연속적으로 가지는 벡터를 만들어 보세요.

In [9]:
import numpy as np 
a = np.arange(10,50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


### 5. 4번에서 생성한 벡터를 역순으로 출력하는 코드를 작성하세요.

In [13]:
import numpy as np 
a = np.arange(10,50)
b = a[::-1]
print(b)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


### 6. 0에서 8까지의 값을 가지는 1차원 배열을 3x3(2차원) 배열로 바꿔보세요.

In [15]:
import numpy as np 
a = np.arange(0,9)
print(a)
b = a.reshape(3,3)
print(b)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


### 7. [1,2,0,0,4,0]에서 0이 아닌 원소의 위치를 저장한 배열을 만들어 보세요. (array[0,1,4]가 출력되도록 합니다.)

In [21]:
import numpy as np
a = np.array([1,2,0,0,4,0])
b = np.where(a != 0)
print(b)

(array([0, 1, 4], dtype=int64),)


### 8. 랜덤값을 갖는 3x3x3 배열을 생성하세요.

In [23]:
import numpy as np
a = np.random.random((3,3,3))
a

array([[[0.31647362, 0.20676407, 0.78087297],
        [0.31207231, 0.19804703, 0.11477568],
        [0.38723378, 0.34891199, 0.22137707]],

       [[0.90361117, 0.01951497, 0.34532521],
        [0.65136517, 0.42182266, 0.32022967],
        [0.25866209, 0.21313443, 0.20283813]],

       [[0.93091298, 0.01947036, 0.89298747],
        [0.60661268, 0.37888613, 0.1931693 ],
        [0.08099431, 0.67748346, 0.42424929]]])

### 9. 랜덤하게 생성된 10x10 배열의 최대, 최소 값을 찾아 출력하라.

In [24]:
import numpy as np
a = np.random.random((3,3,3))
a

array([[[0.70884374, 0.87426315, 0.5363807 ],
        [0.31678326, 0.22851778, 0.96190649],
        [0.81096662, 0.30178271, 0.3888927 ]],

       [[0.60487785, 0.7776044 , 0.43509179],
        [0.90733456, 0.0895901 , 0.11731288],
        [0.17227129, 0.8652594 , 0.52531152]],

       [[0.97657329, 0.66092893, 0.16917276],
        [0.79396199, 0.20252508, 0.83371904],
        [0.82453505, 0.45961692, 0.97836089]]])

### 10. 30개의 랜덤한 정수값을 갖는 배열을 생성하고, 모든 값의 평균을 출력하라.

### 11. 10x10 배열을 가장 외곽은 모두 1, 안쪽은 모두 0으로 채워지도록 생성하라

### 12. 11과 반대로 외곽은 모두 0, 안쪽은 모두 1이 채워지도록 하라.

### 13. 8x8 배열에서 홀수 열은 0,1 순으로 반복되도록 채워라.

### 14. 정규분포를 따르는 5x5 배열의 랜덤 값을 생성하라.

### 15. 0에서 10까지의 10개의 데이터를 1차원 배열에 생성하고, 4~7만 음수로 바꾸는 코드를 작성하라.
#### ex) [0,1,2,3,-4,-5,-6,-7,8,9,10]

### 16. 랜덤하게 생성된 10개의 값에서 가장 큰 값을 0으로 채워라.

### 17. 다음 2차원 배열을 생성하고, 아래 1),2),3)과 같이 출력하라.